# Generated by Django 2.2.7 on 2019-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no_of_visits', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
